exports.constants = {
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  INTERNAL_SERVER_ERROR: 500,
  SUCCESS: 200,
  CREATED: 201,
  UPDATED: 202,
  DELETED: 204,
  UNAUTHORIZED_ACCESS: "Unauthorized access",
  NOT_FOUND_ERROR: "Not Found",
  INTERNAL_SERVER_ERROR_MSG: "Internal Server Error",
  GENERIC_ERROR: "An error occurred",
  INTERNAL_ERROR: "Internal app error",
  NO_ID: "No ID provided",

  CONTACTS_ROUTE: "/api/contacts",
  CONTACTS_ID_ROUTE: "/api/contacts/:id",
  CONTACTS_NOT_FOUND: "Contact not found",
  CONTACTS_CREATED: "Contact created successfully",
  CONTACTS_UPDATED: "Contact updated successfully",
  CONTACTS_DELETED: "Contact deleted successfully",
  CONTACTS_ALL_FIELDS: "All fields are mandatory.",
  CONTACTS_GET_ALL: "Get contacts",
  CONTACTS_GET_BY_ID: "Get contact by ID",
  CONTACTS_CREATE: "Create contact",
  CONTACTS_UPDATE: "Update contact",
  CONTACTS_DELETE: "Delete contact",
};
